### ISSUE TITLE
Missing tz/user/certs

### ISSUE THREAD

**Issue by hazcod** [umirode/go-mg-net#1]
Hi,

FYI, your Dockerfile template is missing following things:
1. Timezone data file
2. Unprivileged user (can be important to twhart kernel vulnerabilities)
3. Root certificates

Reference: https://github.com/ironPeakServices/iron-scratch/blob/master/Dockerfile

**Comment by umirode** [comment]
Hi,

Thanks for the help. Updated Dockerfile https://github.com/umirode/go-mg-net/commit/f60d5ac3c0ca15ecdb29b80820bf7a09bc1539c8.

**Comment by hazcod** [comment]
FYI @umirode , also don't forget to set sane defaults for `http.Server`: https://ieftimov.com/post/make-resilient-golang-net-http-servers-using-timeouts-deadlines-context-cancellation/
